import path from 'path'
import fs from 'fs'
import Promise from 'bluebird'

const fsp = Promise.promisifyAll(fs)

async function writeDockerfile(dirPath, image) {
  const fileContent = [
    `FROM ${image}`,
    '',
    'RUN mkdir -p /usr/src/app',
    'WORKDIR /usr/src/app',
    '',
    'COPY . /usr/src/app',
    '',
    // TODO remove this hardcoded command later on?!
    'CMD ["/bin/sh"]',
    '',
    '# THIS IS AN AUTOGENERATED FILE',
    ''
  ].join('\n')

  const dockerfilePath = path.join(dirPath, '.pipeline.dockerfile')
  await fsp.writeFileAsync(dockerfilePath, fileContent, 'utf8')
  return dockerfilePath
}

export default writeDockerfile
